def exception_check(a, b):
    try:
        print(a/b)
    except:
        print('The Error!')